@startuml

/' Objects '/
class User::Private {
  +std::string name;
  +int age;
  +Private(User* q)
  +~Private()
  +q_ptr : User* const
}

class User {
  +User()
  +User (const std::string &name, int age)
  +std::string name() const
  +int age() const
  +void setAge (int age)
  +void setName (const std::string &name)
  #User(Private& dd)
  +~User()
  #d_ptr : std::unique_ptr<Private>
}

/' Inheritance relationships '/

/' Aggregation relationships '/
.User::Private o-- .User

/' Nested objects '/

@enduml
