name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3.5.3
    - uses: threeal/cmake-action@v1.2.0
    - name: Build the project with CMake
      run: cmake --build build
